#ifndef PARSER_H
#define PARSER_H

#include "lexer.h"
#include "ast.h"

// ============================================================
// PARSER CONFIGURATION
// ============================================================

#define MAX_PARSE_ERRORS 256 // Maximum number of parse errors to store

// ============================================================
// PARSE ERROR STRUCTURE
// ============================================================

/**
 * Structure representing a single parsing error
 */
typedef struct
{
    char message[1024]; // Human-readable error message
    int line;           // Line number where error occurred
    int col;            // Column number where error occurred
} ParseError;

// ============================================================
// PARSE RESULT STRUCTURE
// ============================================================

/**
 * Structure containing the result of parsing
 * Includes the AST and any errors encountered
 */
typedef struct
{
    ASTNode *ast;                        // Root of the Abstract Syntax Tree (NULL on failure)
    ParseError errors[MAX_PARSE_ERRORS]; // Array of parse errors
    int error_count;                     // Number of errors encountered
    int success;                         // 1 if parsing succeeded, 0 if errors occurred
} ParseResult;

// ============================================================
// PARSER FUNCTION
// ============================================================

/**
 * Parse a list of tokens into an Abstract Syntax Tree (AST)
 *
 * The parser implements a recursive-descent parser for the Simply language.
 * It follows the grammar with precedence levels:
 *
 *   Program      -> StatementList
 *   StatementList -> Statement StatementList | ε
 *   Statement    -> Declaration | Assignment | Output | Input |
 *                   Conditional | Loop | TaskDecl | TaskCall | Give
 *   Expression   -> LogicalOr
 *   LogicalOr    -> LogicalAnd (|| LogicalAnd)*
 *   LogicalAnd   -> Equality (&& Equality)*
 *   Equality     -> Relational (== | != Relational)*
 *   Relational   -> Additive (< | > | <= | >= Additive)*
 *   Additive     -> Multiplicative (+ | - Multiplicative)*
 *   Multiplicative -> Unary (* | / | % Unary)*
 *   Unary        -> ! Unary | - Unary | Primary
 *   Primary      -> INTEGER | DECIMAL | STRING | BOOLEAN |
 *                   IDENTIFIER | ( Expression )
 *
 * @param tokens - TokenList generated by the lexer
 * @return       - ParseResult containing:
 *                   - ast: Root AST node (if successful)
 *                   - errors: Array of parse errors (if any)
 *                   - error_count: Number of errors
 *                   - success: Boolean success flag
 *
 * Example:
 *   Input: make x = 10
 *   Output AST:
 *     PROGRAM
 *       STATEMENT_LIST
 *         DECLARATION
 *           IDENTIFIER 'x'
 *           INTEGER '10'
 */
ParseResult parser_parse(TokenList *tokens);

#endif // PARSER_H